using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.NetworkInformation;
using System.Net.Sockets;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;

namespace CustomWinConsole;

public static class CommandsExtra3
{
    public static void Register(Dictionary<string, Action<string[]>> builtins)
    {
        builtins["atan2"] = a => { if (a.Length >= 2 && double.TryParse(a[0], out double y) && double.TryParse(a[1], out double x)) Console.WriteLine($"  {Math.Atan2(y, x):F6} rad"); };
        builtins["sinh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {Math.Sinh(v):F6}"); };
        builtins["cosh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {Math.Cosh(v):F6}"); };
        builtins["tanh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {Math.Tanh(v):F6}"); };
        builtins["asinh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {MathF.Asinh((float)v):F6}"); };
        builtins["acosh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {MathF.Acosh((float)v):F6}"); };
        builtins["atanh"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {MathF.Atanh((float)v):F6}"); };
        builtins["clamp"] = a => { if (a.Length >= 3 && double.TryParse(a[0], out double val) && double.TryParse(a[1], out double min) && double.TryParse(a[2], out double max)) Console.WriteLine($"  {Math.Clamp(val, min, max):F4}"); };
        builtins["lerp"] = a => { if (a.Length >= 3 && double.TryParse(a[0], out double a1) && double.TryParse(a[1], out double b) && double.TryParse(a[2], out double t)) Console.WriteLine($"  {a1 + (b - a1) * t:F4}"); };
        builtins["sign"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine($"  {Math.Sign(v)}"); };
        builtins["mod"] = a => { if (a.Length >= 2 && double.TryParse(a[0], out double n) && double.TryParse(a[1], out double d) && d != 0) Console.WriteLine($"  {n % d:F4}"); };
        builtins["divmod"] = a => { if (a.Length >= 2 && double.TryParse(a[0], out double n) && double.TryParse(a[1], out double d) && d != 0) Console.WriteLine($"  ({Math.Floor(n / d):F0}, {n % d:F4})"); };
        builtins["bitand"] = a => { if (a.Length >= 2 && int.TryParse(a[0], out int x) && int.TryParse(a[1], out int y)) Console.WriteLine($"  {x & y}"); };
        builtins["bitor"] = a => { if (a.Length >= 2 && int.TryParse(a[0], out int x) && int.TryParse(a[1], out int y)) Console.WriteLine($"  {x | y}"); };
        builtins["bitxor"] = a => { if (a.Length >= 2 && int.TryParse(a[0], out int x) && int.TryParse(a[1], out int y)) Console.WriteLine($"  {x ^ y}"); };
        builtins["bitnot"] = a => { if (a.Length > 0 && int.TryParse(a[0], out int x)) Console.WriteLine($"  {~x}"); };
        builtins["bitshiftl"] = a => { if (a.Length >= 2 && int.TryParse(a[0], out int x) && int.TryParse(a[1], out int n)) Console.WriteLine($"  {x << n}"); };
        builtins["bitshiftr"] = a => { if (a.Length >= 2 && int.TryParse(a[0], out int x) && int.TryParse(a[1], out int n)) Console.WriteLine($"  {x >> n}"); };
        builtins["isodd"] = a => { if (a.Length > 0 && int.TryParse(a[0], out int n)) Console.WriteLine(n % 2 != 0 ? "  true" : "  false"); };
        builtins["iseven"] = a => { if (a.Length > 0 && int.TryParse(a[0], out int n)) Console.WriteLine(n % 2 == 0 ? "  true" : "  false"); };
        builtins["ispos"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine(v > 0 ? "  true" : "  false"); };
        builtins["isneg"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine(v < 0 ? "  true" : "  false"); };
        builtins["iszero"] = a => { if (a.Length > 0 && double.TryParse(a[0], out double v)) Console.WriteLine(v == 0 ? "  true" : "  false"); };
        builtins["between"] = a => { if (a.Length >= 3 && double.TryParse(a[0], out double v) && double.TryParse(a[1], out double lo) && double.TryParse(a[2], out double hi)) Console.WriteLine(v >= lo && v <= hi ? "  true" : "  false"); };
        builtins["closest"] = a => { if (a.Length >= 2) { double target = double.Parse(a[0]); var nums = a.Skip(1).Select(double.Parse).ToList(); Console.WriteLine($"  {nums.OrderBy(x => Math.Abs(x - target)).First():F4}"); } };
        builtins["farthest"] = a => { if (a.Length >= 2) { double target = double.Parse(a[0]); var nums = a.Skip(1).Select(double.Parse).ToList(); Console.WriteLine($"  {nums.OrderByDescending(x => Math.Abs(x - target)).First():F4}"); } };
        builtins["rank"] = a => { if (a.Length >= 2 && double.TryParse(a[0], out double val)) { var nums = a.Skip(1).Select(double.Parse).OrderBy(x => x).ToList(); Console.WriteLine($"  {nums.IndexOf(val) + 1}"); } };
        builtins["percentile"] = a => { if (a.Length >= 2) { double p = double.Parse(a[0]); var nums = a.Skip(1).Select(double.Parse).OrderBy(x => x).ToList(); int idx = (int)Math.Ceiling(p / 100.0 * nums.Count) - 1; Console.WriteLine($"  {nums[Math.Clamp(idx, 0, nums.Count - 1)]:F4}"); } };

        builtins["left"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n)) Console.WriteLine("  " + a[0][..Math.Min(n, a[0].Length)]); };
        builtins["right"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n)) { string s = a[0]; Console.WriteLine("  " + s[Math.Max(0, s.Length - n)..]); } };
        builtins["mid"] = a => { if (a.Length >= 3 && int.TryParse(a[1], out int start) && int.TryParse(a[2], out int len)) { string s = a[0]; int s0 = Math.Max(0, Math.Min(start, s.Length)); Console.WriteLine("  " + s.Substring(s0, Math.Min(len, s.Length - s0))); } };
        builtins["repeatstr"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n)) Console.WriteLine("  " + string.Concat(Enumerable.Repeat(a[0], n))); };
        builtins["reverse"] = a => { if (a.Length > 0) Console.WriteLine("  " + new string(a[0].Reverse().ToArray())); };
        builtins["sortchars"] = a => { if (a.Length > 0) Console.WriteLine("  " + new string(a[0].OrderBy(c => c).ToArray())); };
        builtins["dedup"] = a => { if (a.Length > 0) Console.WriteLine("  " + new string(a[0].Distinct().ToArray())); };
        builtins["countchar"] = a => { if (a.Length >= 2) Console.WriteLine($"  {a[0].Count(c => c == a[1][0])}"); };
        builtins["indexof"] = a => { if (a.Length >= 2) Console.WriteLine($"  {a[0].IndexOf(a[1])}"); };
        builtins["lastindexof"] = a => { if (a.Length >= 2) Console.WriteLine($"  {a[0].LastIndexOf(a[1])}"); };
        builtins["startswith"] = a => { if (a.Length >= 2) Console.WriteLine(a[0].StartsWith(a[1]) ? "  true" : "  false"); };
        builtins["endswith"] = a => { if (a.Length >= 2) Console.WriteLine(a[0].EndsWith(a[1]) ? "  true" : "  false"); };
        builtins["contains"] = a => { if (a.Length >= 2) Console.WriteLine(a[0].Contains(a[1]) ? "  true" : "  false"); };
        builtins["countwords"] = a => Console.WriteLine($"  {string.Join(" ", a).Split(' ', StringSplitOptions.RemoveEmptyEntries).Length} words");
        builtins["countlines"] = a => Console.WriteLine($"  {string.Join(" ", a).Split('\n').Length} lines");
        builtins["chars"] = a => { if (a.Length > 0) { Console.WriteLine($"  Length: {a[0].Length}"); foreach (char c in a[0]) Console.Write($"  {(int)c} "); Console.WriteLine(); } };
        builtins["hexstring"] = a => Console.WriteLine("  " + BitConverter.ToString(Encoding.UTF8.GetBytes(string.Join(" ", a))).Replace("-", " "));
        builtins["fromhex"] = a => { try { var bytes = a[0].Replace(" ", "").Chunk(2).Select(h => Convert.ToByte(new string(h), 16)).ToArray(); Console.WriteLine("  " + Encoding.UTF8.GetString(bytes)); } catch { } };
        builtins["charat"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int idx) && idx >= 0 && idx < a[0].Length) Console.WriteLine($"  '{a[0][idx]}'"); };
        builtins["slice"] = a => { if (a.Length >= 3 && int.TryParse(a[1], out int s) && int.TryParse(a[2], out int e)) { string str = a[0]; int s0 = Math.Max(0, Math.Min(s, str.Length)); int e0 = Math.Max(s0, Math.Min(e, str.Length)); Console.WriteLine("  " + str[s0..e0]); } };
        builtins["trimstart"] = a => { if (a.Length > 0) Console.WriteLine("  " + a[0].TrimStart()); };
        builtins["trimend"] = a => { if (a.Length > 0) Console.WriteLine("  " + a[0].TrimEnd()); };
        builtins["stringlength"] = a => { if (a.Length > 0) Console.WriteLine($"  {a[0].Length}"); };
        builtins["isempty"] = a => { if (a.Length > 0) Console.WriteLine(string.IsNullOrEmpty(a[0]) ? "  true" : "  false"); };
        builtins["iswhitespace"] = a => { if (a.Length > 0) Console.WriteLine(string.IsNullOrWhiteSpace(a[0]) ? "  true" : "  false"); };
        builtins["normalize"] = a => { if (a.Length > 0) Console.WriteLine("  " + a[0].Normalize(NormalizationForm.FormC)); };
        builtins["escape"] = a => { if (a.Length > 0) Console.WriteLine("  " + WebUtility.HtmlEncode(string.Join(" ", a))); };
        builtins["unescape"] = a => { if (a.Length > 0) Console.WriteLine("  " + WebUtility.HtmlDecode(string.Join(" ", a))); };
        builtins["wordwrap"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int width)) { string text = a[0]; var words = text.Split(' '); var lines2 = new List<string>(); var line = new StringBuilder(); foreach (var w in words) { if (line.Length + w.Length + 1 > width) { lines2.Add(line.ToString()); line.Clear(); } if (line.Length > 0) line.Append(' '); line.Append(w); } if (line.Length > 0) lines2.Add(line.ToString()); Console.WriteLine(string.Join("\n", lines2)); } };

        builtins["readfile"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine(File.ReadAllText(a[0])); };
        builtins["readlines"] = a => { if (a.Length > 0 && File.Exists(a[0])) foreach (var l in File.ReadAllLines(a[0])) Console.WriteLine(l); };
        builtins["writefile"] = a => { if (a.Length >= 2) { File.WriteAllText(a[0], a[1]); Console.WriteLine("  Written"); } };
        builtins["appendfile"] = a => { if (a.Length >= 2) { File.AppendAllText(a[0], a[1]); Console.WriteLine("  Appended"); } };
        builtins["filecopy"] = a => { if (a.Length >= 2 && File.Exists(a[0])) { File.Copy(a[0], a[1], true); Console.WriteLine("  Copied"); } };
        builtins["filerename"] = a => { if (a.Length >= 2 && File.Exists(a[0])) { File.Move(a[0], a[1]); Console.WriteLine("  Renamed"); } };
        builtins["filedelete"] = a => { if (a.Length > 0 && File.Exists(a[0])) { File.Delete(a[0]); Console.WriteLine("  Deleted"); } };
        builtins["mkdirp"] = a => { if (a.Length > 0) { Directory.CreateDirectory(a[0]); Console.WriteLine("  Created"); } };
        builtins["rmdir"] = a => { if (a.Length > 0 && Directory.Exists(a[0])) { Directory.Delete(a[0], true); Console.WriteLine("  Deleted"); } };
        builtins["lsr"] = a => { if (a.Length > 0 && Directory.Exists(a[0])) foreach (var f in Directory.GetFiles(a[0], "*", SearchOption.AllDirectories)) Console.WriteLine(f); };
        builtins["findfiles"] = a => { if (a.Length >= 2 && Directory.Exists(a[0])) foreach (var f in Directory.GetFiles(a[0], a[1], SearchOption.AllDirectories)) Console.WriteLine(f); };
        builtins["findexec"] = a => { if (a.Length > 0 && Directory.Exists(Directory.GetCurrentDirectory())) foreach (var f in Directory.GetFiles(Directory.GetCurrentDirectory(), a[0], SearchOption.AllDirectories)) Console.WriteLine(f); };
        builtins["md5sum"] = a => { if (a.Length > 0 && File.Exists(a[0])) { var md5 = MD5.HashData(File.ReadAllBytes(a[0])); Console.WriteLine("  " + Convert.ToHexString(md5).ToLower()); } };
        builtins["sha1sum"] = a => { if (a.Length > 0 && File.Exists(a[0])) { var sha1 = SHA1.HashData(File.ReadAllBytes(a[0])); Console.WriteLine("  " + Convert.ToHexString(sha1).ToLower()); } };
        builtins["sha512"] = a => { if (a.Length > 0 && File.Exists(a[0])) { var sha = SHA512.HashData(File.ReadAllBytes(a[0])); Console.WriteLine("  " + Convert.ToHexString(sha).ToLower()); } };
        builtins["filehead"] = a => { if (a.Length >= 2 && File.Exists(a[0]) && int.TryParse(a[1], out int n)) foreach (var l in File.ReadAllLines(a[0]).Take(n)) Console.WriteLine(l); };
        builtins["filetail"] = a => { if (a.Length >= 2 && File.Exists(a[0]) && int.TryParse(a[1], out int n)) foreach (var l in File.ReadAllLines(a[0]).TakeLast(n)) Console.WriteLine(l); };
        builtins["fileseek"] = a => { if (a.Length >= 2 && File.Exists(a[0])) { foreach (var (line, i) in File.ReadAllLines(a[0]).Select((l, i) => (l, i))) if (line.Contains(a[1])) Console.WriteLine($"  {i + 1}: {line}"); } };
        builtins["filecount"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine($"  {File.ReadAllLines(a[0]).Length} lines"); };
        builtins["filewordcount"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine($"  {File.ReadAllText(a[0]).Split(' ', StringSplitOptions.RemoveEmptyEntries).Length} words"); };
        builtins["filesizebytes"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine($"  {new FileInfo(a[0]).Length} bytes"); };
        builtins["filedate"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine($"  {File.GetLastWriteTime(a[0]):yyyy-MM-dd HH:mm:ss}"); };
        builtins["filecreated"] = a => { if (a.Length > 0 && File.Exists(a[0])) Console.WriteLine($"  {File.GetCreationTime(a[0]):yyyy-MM-dd HH:mm:ss}"); };
        builtins["fileext"] = a => { if (a.Length > 0) Console.WriteLine($"  {Path.GetExtension(a[0])}"); };
        builtins["filenameonly"] = a => { if (a.Length > 0) Console.WriteLine($"  {Path.GetFileName(a[0])}"); };
        builtins["filepathonly"] = a => { if (a.Length > 0) Console.WriteLine($"  {Path.GetDirectoryName(a[0])}"); };
        builtins["absPath"] = a => { if (a.Length > 0) Console.WriteLine($"  {Path.GetFullPath(a[0])}"); };
        builtins["relpath"] = a => { if (a.Length >= 2) { Uri from = new(Path.GetFullPath(a[0])); Uri to = new(Path.GetFullPath(a[1])); Console.WriteLine("  " + from.MakeRelativeUri(to).ToString().Replace('/', Path.DirectorySeparatorChar)); } };
        builtins["isabsolute"] = a => { if (a.Length > 0) Console.WriteLine(Path.IsPathRooted(a[0]) ? "  true" : "  false"); };
        builtins["tempdir"] = _ => Console.WriteLine($"  {Path.GetTempPath()}");
        builtins["tempfile"] = _ => Console.WriteLine($"  {Path.GetTempFileName()}");
        builtins["userprofile"] = _ => Console.WriteLine($"  {Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)}");
        builtins["desktop"] = _ => Console.WriteLine($"  {Environment.GetFolderPath(Environment.SpecialFolder.Desktop)}");
        builtins["documents"] = _ => Console.WriteLine($"  {Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments)}");
        builtins["downloads"] = _ => Console.WriteLine($"  {Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), "Downloads")}");
        builtins["appdata"] = _ => Console.WriteLine($"  {Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData)}");
        builtins["programfiles"] = _ => Console.WriteLine($"  {Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles)}");
        builtins["currentdir"] = _ => Console.WriteLine($"  {Directory.GetCurrentDirectory()}");
        builtins["drives"] = _ => { foreach (var d in DriveInfo.GetDrives()) if (d.IsReady) Console.WriteLine($"  {d.Name} {d.TotalSize / 1073741824.0:F1}GB free:{d.AvailableFreeSpace / 1073741824.0:F1}GB"); };
        builtins["dirsize"] = a => { if (a.Length > 0 && Directory.Exists(a[0])) { long size = Directory.GetFiles(a[0], "*", SearchOption.AllDirectories).Sum(f => new FileInfo(f).Length); Console.WriteLine($"  {size / 1048576.0:F2} MB"); } };
        builtins["copydir"] = a => { if (a.Length >= 2 && Directory.Exists(a[0])) { foreach (string dirPath in Directory.GetDirectories(a[0], "*", SearchOption.AllDirectories)) Directory.CreateDirectory(dirPath.Replace(a[0], a[1])); foreach (string filePath in Directory.GetFiles(a[0], "*", SearchOption.AllDirectories)) File.Copy(filePath, filePath.Replace(a[0], a[1]), true); Console.WriteLine("  Copied"); } };

        builtins["memused"] = _ => { try { using var proc = Process.GetCurrentProcess(); Console.WriteLine($"  {proc.WorkingSet64 / 1048576.0:F1} MB"); } catch { Console.WriteLine("  N/A"); } };
        builtins["mempeak"] = _ => { try { using var proc = Process.GetCurrentProcess(); Console.WriteLine($"  {proc.PeakWorkingSet64 / 1048576.0:F1} MB"); } catch { Console.WriteLine("  N/A"); } };
        builtins["cputime"] = _ => { try { using var proc = Process.GetCurrentProcess(); Console.WriteLine($"  {proc.TotalProcessorTime.TotalSeconds:F2}s"); } catch { Console.WriteLine("  N/A"); } };
        builtins["threads"] = _ => { try { using var proc = Process.GetCurrentProcess(); Console.WriteLine($"  {proc.Threads.Count} threads"); } catch { Console.WriteLine("  N/A"); } };
        builtins["handles"] = _ => { try { using var proc = Process.GetCurrentProcess(); Console.WriteLine($"  {proc.HandleCount} handles"); } catch { Console.WriteLine("  N/A"); } };
        builtins["modules"] = _ => { try { using var proc = Process.GetCurrentProcess(); foreach (ProcessModule m in proc.Modules) Console.WriteLine($"  {m.ModuleName}"); } catch { } };
        builtins["uptime"] = _ => Console.WriteLine($"  {(DateTime.Now - Process.GetCurrentProcess().StartTime).TotalHours:F2}h");
        builtins["starttime"] = _ => Console.WriteLine($"  {Process.GetCurrentProcess().StartTime:yyyy-MM-dd HH:mm:ss}");
        builtins["prio"] = a => { if (a.Length > 0 && int.TryParse(a[0], out int pid)) { try { var p = Process.GetProcessById(pid); p.PriorityClass = ProcessPriorityClass.High; Console.WriteLine("  Set to High"); } catch { Console.WriteLine("  Process not found"); } } };
        builtins["lowprio"] = a => { if (a.Length > 0 && int.TryParse(a[0], out int pid)) { try { var p = Process.GetProcessById(pid); p.PriorityClass = ProcessPriorityClass.BelowNormal; Console.WriteLine("  Set to BelowNormal"); } catch { Console.WriteLine("  Process not found"); } } };

        builtins["isportopen"] = a => { if (a.Length >= 2) { try { var client = new TcpClient(); client.Connect(a[0], int.Parse(a[1])); client.Close(); Console.WriteLine("  open"); } catch { Console.WriteLine("  closed"); } } };
        builtins["resolveip"] = a => { if (a.Length > 0) { foreach (var addr in Dns.GetHostAddresses(a[0])) Console.WriteLine($"  {addr}"); } };
        builtins["reverseip"] = a => { if (a.Length > 0) { var entry = Dns.GetHostEntry(a[0]); Console.WriteLine($"  {entry.HostName}"); } };
        builtins["pingcount"] = a => { if (a.Length > 0) { try { var ping = new Ping(); var reply = ping.Send(a[0]); Console.WriteLine(reply.Status == IPStatus.Success ? $"  {reply.RoundtripTime}ms" : "  failed"); } catch { Console.WriteLine("  failed"); } } };
        builtins["traceroute"] = a => { if (a.Length > 0) { try { for (int i = 1; i <= 10; i++) { var ping = new Ping(); var reply = ping.Send(a[0], 1000, Encoding.UTF8.GetBytes("ping"), new PingOptions(i, true)); Console.WriteLine($"  {i}: {reply.Status} {reply.RoundtripTime}ms"); } } catch { } } };
        builtins["gethostname"] = _ => Console.WriteLine($"  {Dns.GetHostName()}");
        builtins["getip"] = _ => { foreach (var addr in Dns.GetHostAddresses(Dns.GetHostName())) if (addr.AddressFamily == AddressFamily.InterNetwork) Console.WriteLine($"  {addr}"); };
        builtins["localips"] = _ => { foreach (var iface in NetworkInterface.GetAllNetworkInterfaces()) if (iface.OperationalStatus == OperationalStatus.Up) foreach (var addr in iface.GetIPProperties().UnicastAddresses) if (addr.Address.AddressFamily == AddressFamily.InterNetwork) Console.WriteLine($"  {iface.Name}: {addr.Address}"); };
        builtins["netinterfaces"] = _ => { foreach (var iface in NetworkInterface.GetAllNetworkInterfaces()) Console.WriteLine($"  {iface.Name} ({iface.OperationalStatus})"); };
        builtins["macaddr"] = _ => { foreach (var iface in NetworkInterface.GetAllNetworkInterfaces()) if (iface.OperationalStatus == OperationalStatus.Up && iface.GetPhysicalAddress().ToString() != "") Console.WriteLine($"  {iface.Name}: {iface.GetPhysicalAddress()}"); };
        builtins["getgateway"] = _ => { foreach (var iface in NetworkInterface.GetAllNetworkInterfaces()) if (iface.OperationalStatus == OperationalStatus.Up) foreach (var g in iface.GetIPProperties().GatewayAddresses) Console.WriteLine($"  {iface.Name}: {g.Address}"); };
        builtins["getdns"] = _ => { foreach (var iface in NetworkInterface.GetAllNetworkInterfaces()) if (iface.OperationalStatus == OperationalStatus.Up) foreach (var d in iface.GetIPProperties().DnsAddresses) Console.WriteLine($"  {iface.Name}: {d}"); };
        builtins["httpheaders"] = a => { if (a.Length > 0) { try { var req = (System.Net.HttpWebRequest)WebRequest.Create(a[0]); req.Method = "HEAD"; using var resp = req.GetResponse(); foreach (string key in resp.Headers) Console.WriteLine($"  {key}: {resp.Headers[key]}"); } catch (Exception ex) { Console.WriteLine($"  Error: {ex.Message}"); } } };
        builtins["downloadspeed"] = a => { if (a.Length > 0) { try { var sw = Stopwatch.StartNew(); using var wc = new WebClient(); wc.DownloadData(a[0]); sw.Stop(); Console.WriteLine($"  {sw.ElapsedMilliseconds}ms"); } catch (Exception ex) { Console.WriteLine($"  Error: {ex.Message}"); } } };

        builtins["guid"] = _ => Console.WriteLine($"  {Guid.NewGuid()}");
        builtins["newguid"] = _ => Console.WriteLine($"  {Guid.NewGuid().ToString("N")}");
        builtins["shortguid"] = _ => Console.WriteLine($"  {Guid.NewGuid().ToString("N")[..12]}");
        builtins["isguid"] = a => { if (a.Length > 0) Console.WriteLine(Guid.TryParse(a[0], out _) ? "  true" : "  false"); };
        builtins["newid"] = _ => Console.WriteLine($"  {DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()}-{Random.Shared.Next(1000, 9999)}");
        builtins["newtoken"] = _ => Console.WriteLine($"  {Convert.ToHexString(RandomNumberGenerator.GetBytes(32))}");

        builtins["matchcount"] = a => { if (a.Length >= 2) { try { Console.WriteLine($"  {Regex.Matches(a[0], a[1]).Count}"); } catch { } } };
        builtins["matchall"] = a => { if (a.Length >= 2) { try { foreach (Match m in Regex.Matches(a[0], a[1])) Console.Write($"  '{m.Value}'"); Console.WriteLine(); } catch { } } };
        builtins["firstmatch"] = a => { if (a.Length >= 2) { try { var m = Regex.Match(a[0], a[1]); if (m.Success) Console.WriteLine($"  '{m.Value}' at {m.Index}"); } catch { } } };
        builtins["replace"] = a => { if (a.Length >= 3) Console.WriteLine("  " + a[0].Replace(a[1], a[2])); };
        builtins["replacefirst"] = a => { if (a.Length >= 3) Console.WriteLine("  " + Regex.Replace(a[0], Regex.Escape(a[1]), a[2], RegexOptions.None, TimeSpan.FromSeconds(1))); };
        builtins["replaceall"] = a => { if (a.Length >= 3) Console.WriteLine("  " + Regex.Replace(a[0], a[1], a[2])); };
        builtins["splitat"] = a => { if (a.Length >= 2) { foreach (var part in a[0].Split(a[1])) Console.WriteLine($"  '{part}'"); } };
        builtins["splitlines"] = a => { if (a.Length > 0) foreach (var l in a[0].Split('\n')) Console.WriteLine($"  '{l.TrimEnd('\r')}'"); };
        builtins["splitwords"] = a => { if (a.Length > 0) foreach (var w in a[0].Split(' ', StringSplitOptions.RemoveEmptyEntries)) Console.WriteLine($"  '{w}'"); };
        builtins["take"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n)) Console.WriteLine("  " + string.Join(" ", a.Take(n))); };
        builtins["skip"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n)) Console.WriteLine("  " + string.Join(" ", a.Skip(n))); };
        builtins["first"] = a => { if (a.Length > 0) Console.WriteLine($"  {a[0]}"); };
        builtins["last"] = a => { if (a.Length > 0) Console.WriteLine($"  {a[^1]}"); };
        builtins["nth"] = a => { if (a.Length >= 2 && int.TryParse(a[1], out int n) && n >= 0 && n < a.Length) Console.WriteLine($"  {a[n]}"); };
        builtins["shuffled"] = a => { var list = a.ToList(); for (int i = list.Count - 1; i > 0; i--) { int j = Random.Shared.Next(i + 1); (list[i], list[j]) = (list[j], list[i]); } Console.WriteLine("  " + string.Join(" ", list)); };
        builtins["uniqued"] = a => Console.WriteLine("  " + string.Join(" ", a.Distinct()));
        builtins["flatten"] = a => Console.WriteLine("  " + string.Join(" ", a.SelectMany(x => x.Split(' '))));
        builtins["zipstr"] = a => { if (a.Length >= 2) { var z = a[0].Zip(a[1]); foreach (var (c1, c2) in z) Console.Write($"({c1},{c2})"); Console.WriteLine(); } };
    }
}
